package review;

public class NumberGit {
	
	public static void main(String[] args) {
	
		

		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		System.out.println("I love you zindagim");
		

		

		
	}

}
